import { GEMINI_EVALUATION_MODEL, geminiClient } from '../config/gemini.js';

interface EvaluationInput {
  candidateProfile: unknown;
  generatedResponse: unknown;
}

interface MetricScore {
  score: number;
  reasoning: string;
}

export interface EndpointEvaluation {
  correctness: MetricScore;
  completeness: MetricScore;
  relevance: MetricScore;
  structure: MetricScore;
  faithfulness: MetricScore;
  overallScore: number;
  summary: string;
  actionItems: string[];
}

interface ExpectedQuestion {
  question: string;
  dimension: string;
  anchor: string;
  cognitive_type: string;
  difficulty: string;
  why_this_question: string;
}

const clampScore = (value: unknown) => {
  const n = typeof value === 'number' ? value : Number(value);
  if (Number.isNaN(n)) return 0;
  return Math.max(0, Math.min(10, n));
};

const extractJsonFromModelText = (value: string) => {
  const trimmed = value.trim();
  const fencedMatch = trimmed.match(/```json\s*([\s\S]*?)```/i);
  if (fencedMatch?.[1]) return fencedMatch[1].trim();

  const firstBrace = trimmed.indexOf('{');
  const lastBrace = trimmed.lastIndexOf('}');
  if (firstBrace >= 0 && lastBrace > firstBrace) {
    return trimmed.slice(firstBrace, lastBrace + 1);
  }

  return trimmed;
};

const normalizeMetric = (value: unknown, fallbackReasoning: string): MetricScore => {
  const metric = (value || {}) as Partial<MetricScore>;
  return {
    score: clampScore(metric.score),
    reasoning: String(metric.reasoning || fallbackReasoning),
  };
};

const normalizeEvaluation = (value: unknown): EndpointEvaluation => {
  const raw = (value || {}) as Partial<EndpointEvaluation>;

  const correctness = normalizeMetric(raw.correctness, 'Correctness assessment unavailable.');
  const completeness = normalizeMetric(raw.completeness, 'Completeness assessment unavailable.');
  const relevance = normalizeMetric(raw.relevance, 'Relevance assessment unavailable.');
  const structure = normalizeMetric(raw.structure, 'Structure assessment unavailable.');
  const faithfulness = normalizeMetric(raw.faithfulness, 'Faithfulness assessment unavailable.');

  const computedOverall =
    (correctness.score + completeness.score + relevance.score + structure.score + faithfulness.score) / 5;

  return {
    correctness,
    completeness,
    relevance,
    structure,
    faithfulness,
    overallScore: clampScore(raw.overallScore ?? computedOverall),
    summary: String(raw.summary || 'Evaluation generated by model.'),
    actionItems: Array.isArray(raw.actionItems)
      ? raw.actionItems.map((item) => String(item)).filter(Boolean)
      : [],
  };
};

const tokenize = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((token) => token.length >= 4);

const unique = (items: string[]) => Array.from(new Set(items));

const asQuestions = (generatedResponse: unknown): ExpectedQuestion[] => {
  const questions = (generatedResponse as { questions?: unknown })?.questions;
  if (!Array.isArray(questions)) return [];
  return questions.filter((q): q is ExpectedQuestion => typeof q === 'object' && q !== null).map((q) => {
    const item = q as Partial<ExpectedQuestion>;
    return {
      question: String(item.question || ''),
      dimension: String(item.dimension || ''),
      anchor: String(item.anchor || ''),
      cognitive_type: String(item.cognitive_type || ''),
      difficulty: String(item.difficulty || ''),
      why_this_question: String(item.why_this_question || ''),
    };
  });
};

const scoreStructure = (questions: ExpectedQuestion[]): MetricScore => {
  if (questions.length === 0) {
    return { score: 0, reasoning: 'No valid questions array found in generated response.' };
  }

  const requiredFields: Array<keyof ExpectedQuestion> = [
    'question',
    'dimension',
    'anchor',
    'cognitive_type',
    'difficulty',
    'why_this_question',
  ];

  let validCount = 0;
  for (const q of questions) {
    const hasAllFields = requiredFields.every((field) => q[field].trim().length > 0);
    if (hasAllFields) validCount += 1;
  }

  const ratio = validCount / questions.length;
  const score = clampScore(Math.round(ratio * 10));
  return {
    score,
    reasoning: `${validCount}/${questions.length} questions contain all required output fields.`,
  };
};

const scoreCompleteness = (questions: ExpectedQuestion[], candidateProfile: unknown): MetricScore => {
  const requestedCount = Number((candidateProfile as { requestedCount?: number })?.requestedCount || questions.length);
  if (questions.length === 0) {
    return { score: 0, reasoning: 'No questions generated, so completeness is poor.' };
  }

  const countRatio = requestedCount > 0 ? Math.min(1, questions.length / requestedCount) : 1;
  const nonEmptyWhy = questions.filter((q) => q.why_this_question.trim().length >= 10).length / questions.length;
  const score = clampScore(Math.round(((countRatio * 0.7) + (nonEmptyWhy * 0.3)) * 10));
  return {
    score,
    reasoning: `Generated ${questions.length}/${requestedCount} target questions with rationale coverage ${(nonEmptyWhy * 100).toFixed(0)}%.`,
  };
};

const scoreRelevance = (questions: ExpectedQuestion[], candidateProfile: unknown): MetricScore => {
  if (questions.length === 0) {
    return { score: 0, reasoning: 'No questions to evaluate for relevance.' };
  }

  const profileText = JSON.stringify(candidateProfile || {}).toLowerCase();
  const profileTokens = unique(tokenize(profileText));
  const profileTokenSet = new Set(profileTokens);

  let relevant = 0;
  for (const q of questions) {
    const qTokens = unique(tokenize(`${q.question} ${q.anchor}`));
    const overlaps = qTokens.filter((token) => profileTokenSet.has(token)).length;
    if (overlaps >= 2) relevant += 1;
  }

  const ratio = relevant / questions.length;
  return {
    score: clampScore(Math.round(ratio * 10)),
    reasoning: `${relevant}/${questions.length} questions have strong lexical overlap with candidate profile context.`,
  };
};

const scoreFaithfulness = (questions: ExpectedQuestion[], candidateProfile: unknown): MetricScore => {
  if (questions.length === 0) {
    return { score: 0, reasoning: 'No questions to evaluate for faithfulness.' };
  }

  const profileText = JSON.stringify(candidateProfile || {}).toLowerCase();
  let groundedAnchors = 0;

  for (const q of questions) {
    const anchor = q.anchor.toLowerCase().trim();
    if (!anchor) continue;
    if (profileText.includes(anchor)) {
      groundedAnchors += 1;
      continue;
    }

    const anchorTokens = tokenize(anchor);
    const matchedTokenCount = anchorTokens.filter((token) => profileText.includes(token)).length;
    if (anchorTokens.length > 0 && matchedTokenCount / anchorTokens.length >= 0.6) {
      groundedAnchors += 1;
    }
  }

  const ratio = groundedAnchors / questions.length;
  return {
    score: clampScore(Math.round(ratio * 10)),
    reasoning: `${groundedAnchors}/${questions.length} anchors appear grounded in candidate profile evidence.`,
  };
};

const scoreCorrectness = (
  questions: ExpectedQuestion[],
  structure: MetricScore,
  relevance: MetricScore,
  faithfulness: MetricScore
): MetricScore => {
  if (questions.length === 0) {
    return { score: 0, reasoning: 'No questions generated to verify correctness.' };
  }

  const validDifficulty = new Set(['easy', 'medium', 'hard']);
  const validDimensions = new Set([
    'Curiosity',
    'Depth of Thinking',
    'Learning Ability',
    'Decision-Making',
    'Intellectual Honesty',
  ]);
  const validCognitiveType = new Set(['trade-off', 'reflection', 'counterfactual', 'abstraction', 'failure analysis']);

  let validSchemaSemantics = 0;
  for (const q of questions) {
    if (
      validDifficulty.has(q.difficulty) &&
      validDimensions.has(q.dimension) &&
      validCognitiveType.has(q.cognitive_type)
    ) {
      validSchemaSemantics += 1;
    }
  }

  const schemaRatio = validSchemaSemantics / questions.length;
  const blended = (schemaRatio * 0.4) + (relevance.score / 10 * 0.3) + (faithfulness.score / 10 * 0.3);
  const score = clampScore(Math.round(blended * 10));

  return {
    score,
    reasoning:
      `${validSchemaSemantics}/${questions.length} questions have valid semantic fields. ` +
      `Correctness inferred using schema validity, relevance, and faithfulness signals. ` +
      `Structure baseline score=${structure.score}.`,
  };
};

const deterministicEvaluation = (candidateProfile: unknown, generatedResponse: unknown): EndpointEvaluation => {
  const questions = asQuestions(generatedResponse);

  const structure = scoreStructure(questions);
  const completeness = scoreCompleteness(questions, candidateProfile);
  const relevance = scoreRelevance(questions, candidateProfile);
  const faithfulness = scoreFaithfulness(questions, candidateProfile);
  const correctness = scoreCorrectness(questions, structure, relevance, faithfulness);

  const overallScore = clampScore(
    (correctness.score * 0.25) +
    (completeness.score * 0.15) +
    (relevance.score * 0.2) +
    (structure.score * 0.1) +
    (faithfulness.score * 0.3)
  );

  const actionItems: string[] = [];
  if (structure.score < 8) actionItems.push('Fix response schema compliance for every question object.');
  if (completeness.score < 8) actionItems.push('Improve count/coverage to satisfy all requested constraints.');
  if (relevance.score < 8) actionItems.push('Ground more questions in concrete candidate-specific details.');
  if (faithfulness.score < 8) actionItems.push('Reduce unsupported anchors and ensure all claims are profile-backed.');
  if (correctness.score < 8) actionItems.push('Validate enum fields and align question logic with input evidence.');

  return {
    correctness,
    completeness,
    relevance,
    structure,
    faithfulness,
    overallScore,
    summary: 'Deterministic rubric evaluation completed across 5 quality dimensions.',
    actionItems,
  };
};

const mergeEvaluations = (base: EndpointEvaluation, modelEval: EndpointEvaluation): EndpointEvaluation => {
  const mergeMetric = (a: MetricScore, b: MetricScore): MetricScore => ({
    score: clampScore((a.score * 0.6) + (b.score * 0.4)),
    reasoning: `${a.reasoning} | Model reviewer: ${b.reasoning}`,
  });

  const correctness = mergeMetric(base.correctness, modelEval.correctness);
  const completeness = mergeMetric(base.completeness, modelEval.completeness);
  const relevance = mergeMetric(base.relevance, modelEval.relevance);
  const structure = mergeMetric(base.structure, modelEval.structure);
  const faithfulness = mergeMetric(base.faithfulness, modelEval.faithfulness);

  return {
    correctness,
    completeness,
    relevance,
    structure,
    faithfulness,
    overallScore: clampScore(
      (correctness.score * 0.25) +
      (completeness.score * 0.15) +
      (relevance.score * 0.2) +
      (structure.score * 0.1) +
      (faithfulness.score * 0.3)
    ),
    summary: modelEval.summary || base.summary,
    actionItems: Array.from(new Set([...(base.actionItems || []), ...(modelEval.actionItems || [])])),
  };
};

const evaluateWithModel = async (
  candidateProfile: unknown,
  generatedResponse: unknown
): Promise<EndpointEvaluation> => {
  const model = geminiClient.getGenerativeModel({ model: GEMINI_EVALUATION_MODEL });

  const prompt = `You are a strict evaluator for AI endpoint quality.

Evaluate the GENERATED_RESPONSE against the CANDIDATE_PROFILE and score the following dimensions from 0 to 10:
1) Correctness - factual accuracy
2) Completeness - coverage of required information
3) Relevance - alignment with input
4) Structure - format compliance
5) Faithfulness - no hallucination

Return ONLY valid JSON in this exact shape:
{
  "correctness": { "score": number, "reasoning": "string" },
  "completeness": { "score": number, "reasoning": "string" },
  "relevance": { "score": number, "reasoning": "string" },
  "structure": { "score": number, "reasoning": "string" },
  "faithfulness": { "score": number, "reasoning": "string" },
  "overallScore": number,
  "summary": "string",
  "actionItems": ["string", "string"]
}

Rules:
- Be critical and precise.
- Penalize generic output and format violations.
- Keep reasoning concise but specific.
- No markdown.

CANDIDATE_PROFILE:
${JSON.stringify(candidateProfile, null, 2)}

GENERATED_RESPONSE:
${JSON.stringify(generatedResponse, null, 2)}
`;

  const result = await model.generateContent(prompt);
  const text = result.response.text();
  const jsonText = extractJsonFromModelText(text);
  const parsed = JSON.parse(jsonText);
  return normalizeEvaluation(parsed);
};

export const evaluateGeneratedEndpointResponse = async ({
  candidateProfile,
  generatedResponse,
}: EvaluationInput): Promise<EndpointEvaluation> => {
  const deterministic = deterministicEvaluation(candidateProfile, generatedResponse);

  try {
    const modelEvaluation = await evaluateWithModel(candidateProfile, generatedResponse);
    return mergeEvaluations(deterministic, modelEvaluation);
  } catch {
    return deterministic;
  }
};
